export const PERMISSION_DEFINITIONS = [
  { code: 'inventory.read', name: 'View inventory', module: 'inventory' },
  { code: 'inventory.write', name: 'Manage inventory', module: 'inventory' },
  { code: 'inventory.delete', name: 'Delete inventory', module: 'inventory' },
  {
    code: 'inventory.import',
    name: 'Bulk import inventory',
    module: 'inventory',
  },
  {
    code: 'inventory.adjust',
    name: 'Adjust inventory stock',
    module: 'inventory',
  },
  { code: 'bom.read', name: 'View bills of materials', module: 'bom' },
  { code: 'bom.write', name: 'Manage bills of materials', module: 'bom' },
  {
    code: 'production.read',
    name: 'View production orders',
    module: 'production',
  },
  {
    code: 'production.write',
    name: 'Manage production orders',
    module: 'production',
  },
  {
    code: 'stock_transfer.read',
    name: 'View stock transfers',
    module: 'stock_transfer',
  },
  {
    code: 'stock_transfer.write',
    name: 'Manage stock transfers',
    module: 'stock_transfer',
  },
  { code: 'purchase.read', name: 'View purchases', module: 'purchase' },
  { code: 'purchase.write', name: 'Manage purchases', module: 'purchase' },
  { code: 'sales.read', name: 'View sales', module: 'sales' },
  { code: 'sales.write', name: 'Manage sales', module: 'sales' },
  {
    code: 'sales.negative_stock',
    name: 'Allow negative stock sales',
    module: 'sales',
  },
  {
    code: 'sales.on_behalf',
    name: 'Sell on behalf of another user',
    module: 'sales',
  },
  { code: 'credit.read', name: 'View credits', module: 'credit' },
  { code: 'credit.write', name: 'Manage credit payments', module: 'credit' },
  { code: 'expense.read', name: 'View expenses', module: 'expense' },
  { code: 'expense.write', name: 'Manage expenses', module: 'expense' },
  { code: 'bank.read', name: 'View bank accounts', module: 'bank' },
  { code: 'bank.write', name: 'Manage bank accounts', module: 'bank' },
  { code: 'dashboard.read', name: 'View dashboard', module: 'dashboard' },
  { code: 'reports.read', name: 'View financial reports', module: 'reports' },
  {
    code: 'profit_loss.read',
    name: 'View profit and loss',
    module: 'profit_loss',
  },
  { code: 'users.read', name: 'View users', module: 'users' },
  { code: 'users.write', name: 'Manage users', module: 'users' },
  { code: 'roles.read', name: 'View roles', module: 'roles' },
  {
    code: 'roles.write',
    name: 'Manage roles and permissions',
    module: 'roles',
  },
  { code: 'locations.read', name: 'View locations', module: 'locations' },
  { code: 'locations.write', name: 'Manage locations', module: 'locations' },
  { code: 'suppliers.read', name: 'View suppliers', module: 'suppliers' },
  { code: 'suppliers.write', name: 'Manage suppliers', module: 'suppliers' },
  { code: 'customers.read', name: 'View customers', module: 'customers' },
  { code: 'customers.write', name: 'Manage customers', module: 'customers' },
  { code: 'inquiries.read', name: 'View customer inquiries', module: 'inquiries' },
  {
    code: 'inquiries.write',
    name: 'Manage customer inquiries',
    module: 'inquiries',
  },
] as const;

export const DEFAULT_ROLE_PERMISSIONS: Record<string, string[]> = {
  Admin: PERMISSION_DEFINITIONS.map((p) => p.code),
  'Sales Representative': [
    'sales.read',
    'sales.write',
    'customers.read',
    'customers.write',
    'inquiries.read',
    'inquiries.write',
    'bank.read',
    'bank.write',
    'credit.read',
    'credit.write',
    'dashboard.read',
    'reports.read',
    'profit_loss.read',
    'locations.read',
    'inventory.read',
  ],
  Purchaser: [
    'purchase.read',
    'purchase.write',
    'suppliers.read',
    'suppliers.write',
    'credit.read',
    'credit.write',
    'bank.read',
    'inventory.read',
    'locations.read',
  ],
  'Stock Keeper': [
    'inventory.read',
    'inventory.write',
    'inventory.import',
    'inventory.adjust',
    'bom.read',
    'bom.write',
    'production.read',
    'production.write',
    'stock_transfer.read',
    'stock_transfer.write',
    'locations.read',
  ],
};
